### ISSUE TITLE
SSH port

### ISSUE THREAD

**Issue by ajdevries** [chrisruffalo/ose-gitlab#1]
Hi Chris,

Thanks for the repo, I got gitlab up and running. The only thing that is not working is the SSH port. First of all the `GITLAB_EXTERNAL_SSH_PORT` variable isn't available in the json config. Maybe remove it from the documentation. And I wonder how to get the direct ssh service working.

Is this possible when running openshift on one server (master and node) in a local environment?

Thanks,
AJ

**Comment by chrisruffalo** [comment]
AJ,

I've removed `GITLAB_EXTERNAL_SSH_PORT` from the `oc new-app` command as it doesn't belong there anymore.

To get the external SSH port you need to create a NodePort service using the `gitlab-direct-ssh-service.json`. That file needs to be modified and the external firewall needs to be opened up on whatever external port you have chosen. This should work in any configuration. I should note, however, that this creates a DIRECT PIPE from any node's `external ssh port` to the application. This is a 1:1 mapping of port to application.

I hope that helps.

**Comment by ajdevries** [comment]
Hi Chris,

Thanks for the reply... I got things working but on a port > 30000. I'm trying to setup a service, where it is possible to use port 22. If you have any suggestions or hints let me know ;-)

Thanks so far... Nice project... The production setup will probably be the SELinux variant with higher ports and maybe a separate Redis and PostgreSQL pod.

**Comment by chrisruffalo** [comment]
Ah, ok, so to use that port you need to have a jump/redirect host essentially that can redirect from 22 to 32222. Normally we could use an existing host but that's complicated by the fact that port 22 is already being used.

The port number thing is a limitation of the way that NodePort works. I'm sure that you could add another interface somewhere with a hostname like ssh.git.your.tld and then redirect from 22 on that host to 32222 on the service address that is internal to your OSE instance.

**Comment by ajdevries** [comment]
Yeah that should work... Thanks for the feedback!
